apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dex.fullname" . }}-config
  labels:
    {{- include "dex.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- tpl (toYaml .Values.server.config) . | nindent 4 }}
