apiVersion: v1
kind: Service
metadata:
  name: {{ include "dex.fullname" . }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "dex.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
    - name: matching-grpc
      port: {{ .Values.service.matchingGrpcPort }}
      targetPort: matching-grpc
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
