[workspace]
members = ["crates/dex-core"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/superdurable/dex"
rust-version = "1.88"

[workspace.dependencies]
crc32c = "0.6"
sha2 = "0.10"
stretto = "0.9"
tempfile = "3"
tokio = { version = "1", features = ["sync"] }
