[workspace]
members = [
    "crates/dex-blob-cache",
    "crates/dex-blob-cache-jni",
    "crates/dex-blob-cache-node",
    "crates/dex-blob-cache-python",
    "crates/dex-protocol",
    "crates/dex-sdk",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/superdurable/dex"
rust-version = "1.97"

[workspace.dependencies]
crc32c = "0.6"
dex-blob-cache = { path = "crates/dex-blob-cache", version = "0.1.0" }
dex-protocol = { path = "crates/dex-protocol", version = "0.1.0" }
jni = "0.21"
napi = { version = "3.12.0", default-features = false }
napi-build = "2.4.0"
napi-derive = "3.6.2"
pyo3 = "0.23"
prost = "0.14"
prost-types = "0.14"
protoc-bin-vendored = "3.2"
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
stretto = "0.9"
tempfile = "3"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.14"
tonic-prost = "0.14"
tonic-prost-build = "0.14"
uuid = { version = "1", features = ["v4"] }
