// Copyright (c) 2026 Super Durable, Inc.
//
// Licensed under the Super Durable Source License 1.0.
// You may not use this file except in compliance with the License.
// See the LICENSE file in the repository root.
//
// SPDX-License-Identifier: LicenseRef-Super-Durable-1.0

import { useEffect, useMemo, useState } from 'react';
import { FlowDefinitionGraphView } from '@superdurable/flow-definition-renderer';
import { readResponseJSON } from '@/lib/http';
import type { FlowDefinitionCatalog } from '@/lib/types';

export function FlowRenderingPage() {
  const [catalog, setCatalog] = useState<FlowDefinitionCatalog | null>(null);
  const [selectedID, setSelectedID] = useState('');
  const [error, setError] = useState('');

  useEffect(() => {
    const controller = new AbortController();
    void loadCatalog(controller.signal, setCatalog, setError);
    return () => controller.abort();
  }, []);

  useEffect(() => {
    if (!catalog || catalog.definitions.length === 0) return;
    if (!catalog.definitions.some((definition) => definition.id === selectedID)) {
      setSelectedID(catalog.definitions[0].id);
    }
  }, [catalog, selectedID]);

  const selected = useMemo(
    () => catalog?.definitions.find((definition) => definition.id === selectedID),
    [catalog, selectedID],
  );

  return (
    <div className="page-shell flow-rendering-page">
      <section className="flow-rendering-header">
        <div>
          <p className="eyebrow">Source definitions</p>
          <h1>Flow Rendering</h1>
          <p>Explore statically possible Step paths generated from Go or Python source.</p>
        </div>
        {catalog?.configured && catalog.definitions.length > 0 && (
          <div className="flow-rendering-summary">
            <b>{catalog.definitions.length} JSON files</b>
            <code title={catalog.directory}>{catalog.directory}</code>
          </div>
        )}
      </section>

      {error && <div className="error-banner">{error}</div>}
      {!catalog && !error && <div className="card empty-state"><h3>Loading Flow definitions…</h3></div>}
      {catalog && !catalog.configured && (
        <div className="card empty-state flow-rendering-empty">
          <h3>No Flow rendering directory configured</h3>
          <p>Start Dex with <strong>--flow-rendering-dir PATH</strong> to load Flow Definition Graph JSON files.</p>
        </div>
      )}
      {catalog?.configured && catalog.definitions.length === 0 && (
        <div className="card empty-state flow-rendering-empty">
          <h3>No Flow definitions found</h3>
          <p>Add JSON files generated by <strong>dexcli visualize</strong> to {catalog.directory} and restart Dex.</p>
        </div>
      )}
      {catalog?.configured && catalog.definitions.length > 0 && (
        <div className="flow-rendering-workspace">
          <aside className="flow-definition-browser card">
            <div className="flow-definition-browser-header">
              <div>
                <p className="eyebrow">Loaded directory</p>
                <h2>Flow JSON files</h2>
              </div>
              <span>{catalog.definitions.length}</span>
            </div>
            <div className="flow-definition-file-list">
              {catalog.definitions.map((definition) => (
                <button
                  aria-pressed={definition.id === selectedID}
                  className={definition.id === selectedID ? 'is-selected' : ''}
                  key={definition.id}
                  onClick={() => setSelectedID(definition.id)}
                  title={definition.file}
                  type="button"
                >
                  <span>
                    <b>{definition.flowName}</b>
                    <em className={definition.valid ? 'is-valid' : 'is-invalid'}>
                      {definition.valid ? 'Valid' : 'Diagnostics'}
                    </em>
                  </span>
                  <code>{definition.file}</code>
                  <small>{definition.sourceLanguage} · {definition.sourcePath}</small>
                </button>
              ))}
            </div>
          </aside>
          <div className="flow-rendering-graph">
            {selected && (
              <FlowDefinitionGraphView
                key={selected.id}
                displayName={selected.flowName}
                graph={selected.graph}
              />
            )}
          </div>
        </div>
      )}
    </div>
  );
}

async function loadCatalog(
  signal: AbortSignal,
  setCatalog: (catalog: FlowDefinitionCatalog) => void,
  setError: (message: string) => void,
): Promise<void> {
  try {
    const response = await fetch('/api/flow-definitions', { signal });
    setCatalog(await readResponseJSON<FlowDefinitionCatalog>(response));
  } catch (loadError) {
    if (signal.aborted) return;
    setError(loadError instanceof Error ? loadError.message : 'Flow definitions failed to load');
  }
}
