// Copyright (c) 2023-2026 Super Durable, Inc.
//
// This file is part of Dex
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type addLicenseHeaderTask struct {
	license    string
	config     *config
	replaceAll bool
}

type config struct {
	rootDir    string
	verifyOnly bool
	filePaths  string
}

const licenseFileName = "./script/licenseheader.txt"

var (
	dirDenylist = []string{"vendor/"}
	defaultFilePerms = os.FileMode(0644)
)

func main() {
	var cfg config
	var replaceAll bool
	flag.StringVar(&cfg.rootDir, "rootDir", ".", "project root directory")
	flag.BoolVar(&cfg.verifyOnly, "verifyOnly", false,
		"don't automatically add headers, just verify all files")
	flag.BoolVar(&replaceAll, "replace", false,
		"replace existing license headers with the current licenseheader.txt")
	flag.StringVar(&cfg.filePaths, "filePaths", "", "comma separated list of files to process")
	flag.Parse()

	task := &addLicenseHeaderTask{
		config:     &cfg,
		replaceAll: replaceAll,
	}
	if err := task.init(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	if err := task.run(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func (task *addLicenseHeaderTask) init() error {
	data, err := os.ReadFile(filepath.Join(task.config.rootDir, licenseFileName))
	if err != nil {
		return fmt.Errorf("read license file: %w", err)
	}
	commented, err := commentOutLines(string(data))
	if err != nil {
		return fmt.Errorf("comment license header: %w", err)
	}
	task.license = commented
	return nil
}

func (task *addLicenseHeaderTask) run() error {
	if task.config.filePaths != "" {
		paths := strings.Split(task.config.filePaths, ",")
		for _, path := range paths {
			info, err := os.Stat(path)
			if err != nil {
				return err
			}
			if err := task.handleFile(path, info, nil); err != nil {
				return err
			}
		}
		return nil
	}
	return filepath.Walk(task.config.rootDir, task.handleFile)
}

func (task *addLicenseHeaderTask) handleFile(path string, fileInfo os.FileInfo, err error) error {
	if err != nil {
		return err
	}
	if fileInfo.IsDir() {
		if strings.HasPrefix(fileInfo.Name(), "_vendor-") || fileInfo.Name() == ".build" || fileInfo.Name() == ".bin" {
			return filepath.SkipDir
		}
		return nil
	}
	if !mustProcessPath(path) {
		return nil
	}
	if !strings.HasSuffix(fileInfo.Name(), ".go") && !strings.HasSuffix(fileInfo.Name(), ".proto") {
		return nil
	}
	if isFileAutogenerated(path) {
		return nil
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	body := string(data)
	hasHeader := hasLicenseHeader(body)
	if hasHeader && !task.replaceAll {
		return nil
	}
	if task.config.verifyOnly {
		if !hasHeader {
			return fmt.Errorf("%s missing license header", path)
		}
		return nil
	}

	if hasHeader {
		body = stripLicenseHeader(body)
	}
	return os.WriteFile(path, []byte(task.license+body), defaultFilePerms)
}

func hasLicenseHeader(content string) bool {
	scanner := bufio.NewScanner(strings.NewReader(content))
	for i := 0; i < 20 && scanner.Scan(); i++ {
		line := strings.TrimSpace(scanner.Text())
		if isLicenseHeaderLine(line) {
			return true
		}
		if line != "" && !strings.HasPrefix(line, "//") {
			return false
		}
	}
	return false
}

func isLicenseHeaderLine(line string) bool {
	lower := strings.ToLower(line)
	return strings.Contains(lower, "copyright") ||
		strings.Contains(lower, "spdx-license-identifier") ||
		strings.Contains(lower, "gnu affero general public license") ||
		strings.Contains(lower, "this file is part of dex") ||
		strings.Contains(lower, "super durable, inc") ||
		strings.Contains(lower, "this program is free software")
}

func stripLicenseHeader(content string) string {
	lines := strings.Split(content, "\n")
	i := 0
	for i < len(lines) && i < 30 {
		line := strings.TrimSpace(lines[i])
		if line == "" {
			i++
			continue
		}
		if isLicenseHeaderLine(line) || line == "//" {
			i++
			continue
		}
		if strings.HasPrefix(line, "//") {
			// Skip blank comment separators inside the header block.
			i++
			continue
		}
		break
	}
	for i < len(lines) && strings.TrimSpace(lines[i]) == "" {
		i++
	}
	if i >= len(lines) {
		return ""
	}
	return strings.Join(lines[i:], "\n")
}

func isFileAutogenerated(path string) bool {
	return strings.Contains(path, ".gen.") || strings.HasSuffix(path, "_pb.go")
}

func mustProcessPath(path string) bool {
	for _, d := range dirDenylist {
		if strings.Contains(path, d) {
			return false
		}
	}
	return true
}

func commentOutLines(str string) (string, error) {
	var lines []string
	scanner := bufio.NewScanner(strings.NewReader(str))
	for scanner.Scan() {
		text := scanner.Text()
		if text == "" {
			lines = append(lines, "//\n")
		} else {
			lines = append(lines, "// "+text+"\n")
		}
	}
	lines = append(lines, "\n")
	if err := scanner.Err(); err != nil {
		return "", err
	}
	return strings.Join(lines, ""), nil
}
