# Legacy Materials in this file remain under their original licenses.
# See LEGACY_NOTICES.md.

# Modifications Copyright (c) 2026 Super Durable, Inc.
#
# Modifications after the Legacy Cutoff are licensed under the
# Super Durable Source License 1.0.
# Legacy Materials remain under their original licenses.
# See LICENSE and LEGACY_NOTICES.md.

api:
  port: 8801
  includeRPCInputOutputIntoHistory: false
  # Ignored by Cadence; shown for parity with the Temporal template.
  useTemporalSynchronousUpdateForAllRPCs: false
  queryWorkflowFailedRetryPolicy:
    initialInterval: 100ms
    backoffCoefficient: 1
    maximumInterval: 100ms
    maximumAttempts: 5
  invokeRPCContinuedAsNewErrorRetryPolicy:
    initialInterval: 100ms
    backoffCoefficient: 2
    maximumInterval: 1s
    totalDuration: 5s
interpreter:
  attributeIndexSyncTimeout: 2m
  #  interpreterActivityConfig:
  #  disableSystemSearchAttributes: true # (deprecated) set to true if you don't have advanced visibility in Cadence, see more https://github.com/uber/cadence/issues/5085
  #  executingStateIdMode: DISABLED # set to true if you don't have advanced visibility in Cadence, see more https://github.com/uber/cadence/issues/5085
  cadence:
    hostPort: 127.0.0.1:7833
    domain: default
    adminSecurityToken: ""
  defaultWorkflowConfig:
    continueAsNewThreshold: 100
blobStore:
  enabled: true
  thresholdInBytes: 1024
  historyRetentionInDays: 3
  supportedStorages:
    - status: active
      storageId: "local-cadence"
      storageType: "local"
      localDirectory: "./dex-blobs-cadence"
