/*
 * Legacy Materials in this file remain under their original licenses.
 * See LEGACY_NOTICES.md.
 */

/*
 * Modifications Copyright (c) 2026 Super Durable, Inc.
 *
 * Modifications after the Legacy Cutoff are licensed under the
 * Super Durable Source License 1.0.
 * Legacy Materials remain under their original licenses.
 * See LICENSE and LEGACY_NOTICES.md.
 */

package io.superdurable.dex;

import java.time.Duration;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * Configures one {@link Client#startFlow} request.
 *
 * <p>Use the builder for optional timeout, scheduling, retry, initial Attribute, routing, and
 * idempotency settings. Durations sent by the current client must be nonnegative whole seconds
 * within a signed 32-bit range. Unset values use server defaults, and an unset request ID is
 * generated by the SDK.
 *
 * <pre>{@code
 * StartFlowOptions options = StartFlowOptions.newBuilder()
 *         .timeout(Duration.ofHours(1))
 *         .idReusePolicy(IdReusePolicy.ALLOW_IF_PREVIOUS_FAILED)
 *         .addAttribute(priority, 10)
 *         .requestId("start-order-123")
 *         .build();
 * client.startFlow(orderFlow, "order-123", input, options);
 * }</pre>
 */
public final class StartFlowOptions {
    private final Duration timeout;
    private final Duration startDelay;
    private final IdReusePolicy idReusePolicy;
    private final String cronSchedule;
    private final RetryPolicy retryPolicy;
    private final List<AttributeInitialization> attributes;
    private final FlowConfig configOverride;
    private final boolean ignoreAlreadyStarted;
    private final String requestId;

    /** Creates options that use all SDK and server defaults. */
    public StartFlowOptions() {
        this(new Builder());
    }

    private StartFlowOptions(final Builder builder) {
        this.timeout = builder.timeout;
        this.startDelay = builder.startDelay;
        this.idReusePolicy = builder.idReusePolicy;
        this.cronSchedule = builder.cronSchedule;
        this.retryPolicy = builder.retryPolicy;
        this.attributes = Collections.unmodifiableList(
                new ArrayList<AttributeInitialization>(builder.attributes));
        this.configOverride = builder.configOverride;
        this.ignoreAlreadyStarted = builder.ignoreAlreadyStarted;
        this.requestId = builder.requestId;
    }

    /**
     * Creates a builder initialized with start defaults.
     *
     * @return a new mutable builder
     */
    public static Builder newBuilder() {
        return new Builder();
    }

    Duration getTimeout() {
        return timeout;
    }

    Duration getStartDelay() {
        return startDelay;
    }

    IdReusePolicy getIdReusePolicy() {
        return idReusePolicy;
    }

    String getCronSchedule() {
        return cronSchedule;
    }

    RetryPolicy getRetryPolicy() {
        return retryPolicy;
    }

    List<AttributeInitialization> getAttributes() {
        return attributes;
    }

    FlowConfig getConfigOverride() {
        return configOverride;
    }

    boolean isIgnoreAlreadyStarted() {
        return ignoreAlreadyStarted;
    }

    String getRequestId() {
        return requestId;
    }

    /** Builds immutable {@link StartFlowOptions} values. */
    public static final class Builder {
        private Duration timeout;
        private Duration startDelay;
        private IdReusePolicy idReusePolicy = IdReusePolicy.DEFAULT;
        private String cronSchedule;
        private RetryPolicy retryPolicy;
        private final List<AttributeInitialization> attributes =
                new ArrayList<AttributeInitialization>();
        private FlowConfig configOverride;
        private boolean ignoreAlreadyStarted;
        private String requestId;

        private Builder() {
        }

        /**
         * Sets the maximum Flow execution duration.
         *
         * @param value a nonnegative whole-second timeout, or {@code null} for the server default
         * @return this builder
         */
        public Builder timeout(final Duration value) {
            timeout = value;
            return this;
        }

        /**
         * Delays creation of the first Step execution.
         *
         * @param value a nonnegative whole-second delay, or {@code null} for no explicit delay
         * @return this builder
         */
        public Builder startDelay(final Duration value) {
            startDelay = value;
            return this;
        }

        /**
         * Sets how an existing Flow ID may be reused.
         *
         * @param value the reuse policy; the default is {@link IdReusePolicy#DEFAULT}
         * @return this builder
         */
        public Builder idReusePolicy(final IdReusePolicy value) {
            idReusePolicy = value;
            return this;
        }

        /**
         * Sets a server-understood cron schedule for recurring executions.
         *
         * @param value the cron expression, or {@code null} for no schedule
         * @return this builder
         */
        public Builder cronSchedule(final String value) {
            cronSchedule = value;
            return this;
        }

        /**
         * Sets retry behavior for abnormal Flow completion.
         *
         * @param value the Flow retry policy, or {@code null} for no explicit policy
         * @return this builder
         */
        public Builder retryPolicy(final RetryPolicy value) {
            retryPolicy = value;
            return this;
        }

        /**
         * Adds an initial scalar Attribute value atomically with Flow start.
         *
         * @param attribute the nonnull registered Attribute
         * @param value the typed initial value
         * @param <T> the Attribute value type
         * @return this builder
         * @throws NullPointerException if {@code attribute} is {@code null}
         */
        public <T> Builder addAttribute(final Attribute<T> attribute, final T value) {
            attributes.add(new AttributeInitialization(
                    Objects.requireNonNull(attribute, "attribute"),
                    null,
                    value));
            return this;
        }

        /**
         * Adds an initial Attribute-map value atomically with Flow start.
         *
         * @param attributeMap the nonnull registered Attribute map
         * @param instance the nonblank map instance
         * @param value the typed initial value
         * @param <T> the Attribute value type
         * @return this builder
         * @throws NullPointerException if {@code attributeMap} is {@code null}
         * @throws IllegalArgumentException if {@code instance} is {@code null} or blank
         */
        public <T> Builder addAttribute(
                final AttributeMap<T> attributeMap,
                final String instance,
                final T value) {
            attributes.add(new AttributeInitialization(
                    Objects.requireNonNull(attributeMap, "attributeMap"),
                    Attribute.requireName(instance),
                    value));
            return this;
        }

        /**
         * Overrides Flow configuration for the new execution.
         *
         * @param value the per-execution configuration, or {@code null} for defaults
         * @return this builder
         */
        public Builder configOverride(final FlowConfig value) {
            configOverride = value;
            return this;
        }

        /**
         * Controls whether an already-started response is accepted.
         *
         * @param value {@code true} to ignore the already-started error
         * @return this builder
         */
        public Builder ignoreAlreadyStarted(final boolean value) {
            ignoreAlreadyStarted = value;
            return this;
        }

        /**
         * Sets an idempotency key for this start request.
         *
         * @param value the stable request ID, or {@code null} to generate a UUID
         * @return this builder
         */
        public Builder requestId(final String value) {
            requestId = value;
            return this;
        }

        /**
         * Builds immutable start options from the current values.
         *
         * @return the configured start options
         */
        public StartFlowOptions build() {
            return new StartFlowOptions(this);
        }
    }

    static final class AttributeInitialization {
        private final PersistenceDefinition definition;
        private final String instance;
        private final Object value;

        private AttributeInitialization(
                final PersistenceDefinition definition,
                final String instance,
                final Object value) {
            this.definition = definition;
            this.instance = instance;
            this.value = value;
        }

        PersistenceDefinition getDefinition() {
            return definition;
        }

        String getInstance() {
            return instance;
        }

        Object getValue() {
            return value;
        }
    }
}
