POST http://localhost:8801/api/v1/workflow/signal
Content-Type: application/json

{
  "workflowId": "<workflowId>",
  "signalChannelName": "manual-recovery-retry"
}

######
POST http://localhost:8801/api/v1/workflow/signal
Content-Type: application/json

{
  "workflowId": "<workflowId>",
  "signalChannelName": "manual-recovery-skip"
}

###
