[package]
name = "dex-sdk"
description = "Strongly typed Rust SDK for Dex"
version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
dex-blob-cache = { path = "../dex-blob-cache" }
dex-protocol = { path = "../dex-protocol" }
prost.workspace = true
prost-types.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
trybuild = "1.0"
