// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: dex.proto

package dexpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunsService_StartRun_FullMethodName = "/dex.RunsService/StartRun"
)

// RunsServiceClient is the client API for RunsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunsServiceClient interface {
	StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type runsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunsServiceClient(cc grpc.ClientConnInterface) RunsServiceClient {
	return &runsServiceClient{cc}
}

func (c *runsServiceClient) StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RunsService_StartRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunsServiceServer is the server API for RunsService service.
// All implementations must embed UnimplementedRunsServiceServer
// for forward compatibility.
type RunsServiceServer interface {
	StartRun(context.Context, *StartRunRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedRunsServiceServer()
}

// UnimplementedRunsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunsServiceServer struct{}

func (UnimplementedRunsServiceServer) StartRun(context.Context, *StartRunRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRun not implemented")
}
func (UnimplementedRunsServiceServer) mustEmbedUnimplementedRunsServiceServer() {}
func (UnimplementedRunsServiceServer) testEmbeddedByValue()                     {}

// UnsafeRunsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunsServiceServer will
// result in compilation errors.
type UnsafeRunsServiceServer interface {
	mustEmbedUnimplementedRunsServiceServer()
}

func RegisterRunsServiceServer(s grpc.ServiceRegistrar, srv RunsServiceServer) {
	// If the following call pancis, it indicates UnimplementedRunsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunsService_ServiceDesc, srv)
}

func _RunsService_StartRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunsServiceServer).StartRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunsService_StartRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunsServiceServer).StartRun(ctx, req.(*StartRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunsService_ServiceDesc is the grpc.ServiceDesc for RunsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dex.RunsService",
	HandlerType: (*RunsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRun",
			Handler:    _RunsService_StartRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dex.proto",
}
