// Copyright (c) 2023-2026 Super Durable, Inc.
//
// This file is part of Dex
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: dex.proto

package dexpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngineService_StartRun_FullMethodName                   = "/dex.EngineService/StartRun"
	EngineService_RecordStepExecuteCompleted_FullMethodName = "/dex.EngineService/RecordStepExecuteCompleted"
	EngineService_HandleAsyncMatch_FullMethodName           = "/dex.EngineService/HandleAsyncMatch"
)

// EngineServiceClient is the client API for EngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// core service for durable execution runs
type EngineServiceClient interface {
	StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// record APIs are called from workers
	RecordStepExecuteCompleted(ctx context.Context, in *RecordStepExecuteCompletedRequest, opts ...grpc.CallOption) (*RecordStepExecuteCompletedResponse, error)
	// handle APIs are called from Matching service
	HandleAsyncMatch(ctx context.Context, in *HandleAsyncMatchRequest, opts ...grpc.CallOption) (*HandleAsyncMatchResponse, error)
}

type engineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineServiceClient(cc grpc.ClientConnInterface) EngineServiceClient {
	return &engineServiceClient{cc}
}

func (c *engineServiceClient) StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EngineService_StartRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) RecordStepExecuteCompleted(ctx context.Context, in *RecordStepExecuteCompletedRequest, opts ...grpc.CallOption) (*RecordStepExecuteCompletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordStepExecuteCompletedResponse)
	err := c.cc.Invoke(ctx, EngineService_RecordStepExecuteCompleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) HandleAsyncMatch(ctx context.Context, in *HandleAsyncMatchRequest, opts ...grpc.CallOption) (*HandleAsyncMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleAsyncMatchResponse)
	err := c.cc.Invoke(ctx, EngineService_HandleAsyncMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServiceServer is the server API for EngineService service.
// All implementations must embed UnimplementedEngineServiceServer
// for forward compatibility.
//
// core service for durable execution runs
type EngineServiceServer interface {
	StartRun(context.Context, *StartRunRequest) (*emptypb.Empty, error)
	// record APIs are called from workers
	RecordStepExecuteCompleted(context.Context, *RecordStepExecuteCompletedRequest) (*RecordStepExecuteCompletedResponse, error)
	// handle APIs are called from Matching service
	HandleAsyncMatch(context.Context, *HandleAsyncMatchRequest) (*HandleAsyncMatchResponse, error)
	mustEmbedUnimplementedEngineServiceServer()
}

// UnimplementedEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineServiceServer struct{}

func (UnimplementedEngineServiceServer) StartRun(context.Context, *StartRunRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRun not implemented")
}
func (UnimplementedEngineServiceServer) RecordStepExecuteCompleted(context.Context, *RecordStepExecuteCompletedRequest) (*RecordStepExecuteCompletedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordStepExecuteCompleted not implemented")
}
func (UnimplementedEngineServiceServer) HandleAsyncMatch(context.Context, *HandleAsyncMatchRequest) (*HandleAsyncMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleAsyncMatch not implemented")
}
func (UnimplementedEngineServiceServer) mustEmbedUnimplementedEngineServiceServer() {}
func (UnimplementedEngineServiceServer) testEmbeddedByValue()                       {}

// UnsafeEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServiceServer will
// result in compilation errors.
type UnsafeEngineServiceServer interface {
	mustEmbedUnimplementedEngineServiceServer()
}

func RegisterEngineServiceServer(s grpc.ServiceRegistrar, srv EngineServiceServer) {
	// If the following call pancis, it indicates UnimplementedEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngineService_ServiceDesc, srv)
}

func _EngineService_StartRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).StartRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_StartRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).StartRun(ctx, req.(*StartRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_RecordStepExecuteCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordStepExecuteCompletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).RecordStepExecuteCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_RecordStepExecuteCompleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).RecordStepExecuteCompleted(ctx, req.(*RecordStepExecuteCompletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_HandleAsyncMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleAsyncMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).HandleAsyncMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_HandleAsyncMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).HandleAsyncMatch(ctx, req.(*HandleAsyncMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineService_ServiceDesc is the grpc.ServiceDesc for EngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dex.EngineService",
	HandlerType: (*EngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRun",
			Handler:    _EngineService_StartRun_Handler,
		},
		{
			MethodName: "RecordStepExecuteCompleted",
			Handler:    _EngineService_RecordStepExecuteCompleted_Handler,
		},
		{
			MethodName: "HandleAsyncMatch",
			Handler:    _EngineService_HandleAsyncMatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dex.proto",
}

const (
	MatchingService_PollForRun_FullMethodName  = "/dex.MatchingService/PollForRun"
	MatchingService_DispatchRun_FullMethodName = "/dex.MatchingService/DispatchRun"
)

// MatchingServiceClient is the client API for MatchingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// sub system for dispatching to worker, and persisting tasks if worker not available
type MatchingServiceClient interface {
	PollForRun(ctx context.Context, in *PollForRunRequest, opts ...grpc.CallOption) (*PollForRunResponse, error)
	// a short streaming RPC invoked by Engine to dispatch run to worker via matching
	DispatchRun(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DispatchRunMessageFromEngine, DispatchMessageToEngine], error)
}

type matchingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchingServiceClient(cc grpc.ClientConnInterface) MatchingServiceClient {
	return &matchingServiceClient{cc}
}

func (c *matchingServiceClient) PollForRun(ctx context.Context, in *PollForRunRequest, opts ...grpc.CallOption) (*PollForRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollForRunResponse)
	err := c.cc.Invoke(ctx, MatchingService_PollForRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) DispatchRun(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DispatchRunMessageFromEngine, DispatchMessageToEngine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MatchingService_ServiceDesc.Streams[0], MatchingService_DispatchRun_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DispatchRunMessageFromEngine, DispatchMessageToEngine]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatchingService_DispatchRunClient = grpc.BidiStreamingClient[DispatchRunMessageFromEngine, DispatchMessageToEngine]

// MatchingServiceServer is the server API for MatchingService service.
// All implementations must embed UnimplementedMatchingServiceServer
// for forward compatibility.
//
// sub system for dispatching to worker, and persisting tasks if worker not available
type MatchingServiceServer interface {
	PollForRun(context.Context, *PollForRunRequest) (*PollForRunResponse, error)
	// a short streaming RPC invoked by Engine to dispatch run to worker via matching
	DispatchRun(grpc.BidiStreamingServer[DispatchRunMessageFromEngine, DispatchMessageToEngine]) error
	mustEmbedUnimplementedMatchingServiceServer()
}

// UnimplementedMatchingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchingServiceServer struct{}

func (UnimplementedMatchingServiceServer) PollForRun(context.Context, *PollForRunRequest) (*PollForRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollForRun not implemented")
}
func (UnimplementedMatchingServiceServer) DispatchRun(grpc.BidiStreamingServer[DispatchRunMessageFromEngine, DispatchMessageToEngine]) error {
	return status.Errorf(codes.Unimplemented, "method DispatchRun not implemented")
}
func (UnimplementedMatchingServiceServer) mustEmbedUnimplementedMatchingServiceServer() {}
func (UnimplementedMatchingServiceServer) testEmbeddedByValue()                         {}

// UnsafeMatchingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchingServiceServer will
// result in compilation errors.
type UnsafeMatchingServiceServer interface {
	mustEmbedUnimplementedMatchingServiceServer()
}

func RegisterMatchingServiceServer(s grpc.ServiceRegistrar, srv MatchingServiceServer) {
	// If the following call pancis, it indicates UnimplementedMatchingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchingService_ServiceDesc, srv)
}

func _MatchingService_PollForRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollForRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).PollForRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_PollForRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).PollForRun(ctx, req.(*PollForRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_DispatchRun_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MatchingServiceServer).DispatchRun(&grpc.GenericServerStream[DispatchRunMessageFromEngine, DispatchMessageToEngine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatchingService_DispatchRunServer = grpc.BidiStreamingServer[DispatchRunMessageFromEngine, DispatchMessageToEngine]

// MatchingService_ServiceDesc is the grpc.ServiceDesc for MatchingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dex.MatchingService",
	HandlerType: (*MatchingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PollForRun",
			Handler:    _MatchingService_PollForRun_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DispatchRun",
			Handler:       _MatchingService_DispatchRun_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dex.proto",
}

// OperationServiceClient is the client API for OperationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// sub/side system for non-critical operations
type OperationServiceClient interface {
}

type operationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperationServiceClient(cc grpc.ClientConnInterface) OperationServiceClient {
	return &operationServiceClient{cc}
}

// OperationServiceServer is the server API for OperationService service.
// All implementations must embed UnimplementedOperationServiceServer
// for forward compatibility.
//
// sub/side system for non-critical operations
type OperationServiceServer interface {
	mustEmbedUnimplementedOperationServiceServer()
}

// UnimplementedOperationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperationServiceServer struct{}

func (UnimplementedOperationServiceServer) mustEmbedUnimplementedOperationServiceServer() {}
func (UnimplementedOperationServiceServer) testEmbeddedByValue()                          {}

// UnsafeOperationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperationServiceServer will
// result in compilation errors.
type UnsafeOperationServiceServer interface {
	mustEmbedUnimplementedOperationServiceServer()
}

func RegisterOperationServiceServer(s grpc.ServiceRegistrar, srv OperationServiceServer) {
	// If the following call pancis, it indicates UnimplementedOperationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperationService_ServiceDesc, srv)
}

// OperationService_ServiceDesc is the grpc.ServiceDesc for OperationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dex.OperationService",
	HandlerType: (*OperationServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "dex.proto",
}
