import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Intro and Quick Start',
      collapsed: false,
      items: ['intro/what-is-dex', 'quick-start/index'],
    },
    {
      type: 'category',
      label: 'Capabilities Overview',
      link: {type: 'doc', id: 'capabilities/index'},
      items: [
        {
          type: 'category',
          label: 'Basic',
          collapsed: false,
          items: [
            'capabilities/basic/durable-variables',
            'capabilities/basic/branch-and-loop',
            'capabilities/basic/backoff-retry',
            'capabilities/basic/durable-timer',
          ],
        },
        {
          type: 'category',
          label: 'Advanced',
          collapsed: true,
          items: [
            'capabilities/advanced/rpc',
            'capabilities/advanced/channels',
            'capabilities/advanced/fan-out-fan-in',
            'capabilities/advanced/error-handling-saga',
            'capabilities/advanced/multi-threading',
            'capabilities/advanced/locking',
            'capabilities/advanced/waiting',
            'capabilities/advanced/storage-sync',
            'capabilities/advanced/and-more',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Design Patterns',
      link: {type: 'doc', id: 'design-patterns/index'},
      items: [
        'design-patterns/cron',
        'design-patterns/drain-internal-channels',
        'design-patterns/drain-signal-channels',
        'design-patterns/interruptible',
        'design-patterns/intervention',
        'design-patterns/parallel',
        'design-patterns/parent-child',
        'design-patterns/polling',
        'design-patterns/recovery',
        'design-patterns/reminders',
        'design-patterns/resettable-timer',
        'design-patterns/scalable-parallel',
        'design-patterns/storage',
        'design-patterns/timeout',
        'design-patterns/wait-for-step-completion',
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      link: {type: 'doc', id: 'use-cases/index'},
      items: [
        'use-cases/money-transfer',
        'use-cases/microservice-orchestration',
        'use-cases/engagement',
        'use-cases/subscription',
        'use-cases/polling',
        'use-cases/signup',
        'use-cases/job-post',
        'use-cases/shortlist-candidates',
        'use-cases/dataset-deal',
        'use-cases/ai-agent-email',
      ],
    },
    {
      type: 'category',
      label: 'Production',
      link: {type: 'doc', id: 'production/index'},
      items: [
        'production/application-operations',
        'production/server-operations',
        'production/attribute-store',
        'production/versioning',
      ],
    },
    {
      type: 'category',
      label: 'References',
      link: {type: 'doc', id: 'references/index'},
      items: [
        'references/client-apis',
        'references/persistence',
        'references/rpc',
        'references/rpc-locking',
        'references/channels',
        'references/wait-for-step-completion',
        'references/flow-options',
        'references/flow-config',
        'references/step-options',
        'references/compare-with-temporal',
        'references/limitations',
        'references/persistence-vs-locals',
        'references/typescript-sdk',
        'references/hosting-github-pages',
      ],
    },
    'glossary',
  ],
};

export default sidebars;
