// Copyright (c) 2026 Super Durable, Inc.
//
// Licensed under the Sustainable Use License 1.0.
// You may not use this file except in compliance with the License.
// See the LICENSE file in the repository root.
//
// SPDX-License-Identifier: LicenseRef-Sustainable-Use-1.0

package web

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/superdurable/dex/web/api"
)

const maxFlowDefinitionBytes = 8 << 20

var flowDefinitionGroupIDPattern = regexp.MustCompile(`^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$`)
var v2ActionPermissionPattern = regexp.MustCompile(`^[a-z][a-z0-9]*(?:[.-][a-z0-9]+)*$`)

var v2IndexKeyPattern = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_.-]*$`)

type flowDefinitionHandler struct {
	response      []byte
	v2Definitions map[string]api.V2Definition
}

type flowDefinitionCatalog struct {
	Configured  bool             `json:"configured"`
	Directory   string           `json:"directory,omitempty"`
	Definitions []flowDefinition `json:"definitions"`
}

type flowDefinition struct {
	ID             string            `json:"id"`
	File           string            `json:"file"`
	SchemaVersion  string            `json:"schemaVersion"`
	FlowName       string            `json:"flowName"`
	SourceLanguage string            `json:"sourceLanguage"`
	SourcePath     string            `json:"sourcePath"`
	Valid          bool              `json:"valid"`
	Graph          json.RawMessage   `json:"graph"`
	V2             *api.V2Definition `json:"v2,omitempty"`
}

type flowDefinitionHeader struct {
	SchemaVersion string `json:"schemaVersion"`
	Valid         bool   `json:"valid"`
	Source        struct {
		Language string `json:"language"`
		Path     string `json:"path"`
	} `json:"source"`
	Flow struct {
		Name string `json:"name"`
	} `json:"flow"`
	Groups      []json.RawMessage `json:"groups"`
	V2          *api.V2Definition `json:"v2"`
	Nodes       []json.RawMessage `json:"nodes"`
	Edges       []json.RawMessage `json:"edges"`
	Diagnostics []json.RawMessage `json:"diagnostics"`
}

func loadFlowDefinitions(directory string) (*flowDefinitionHandler, error) {
	catalog := flowDefinitionCatalog{Definitions: make([]flowDefinition, 0)}
	v2Definitions := make(map[string]api.V2Definition)
	directory = strings.TrimSpace(directory)
	if directory == "" {
		response, err := json.Marshal(catalog)
		if err != nil {
			return nil, fmt.Errorf("encode empty Flow Definition Graph catalog: %w", err)
		}
		return &flowDefinitionHandler{response: response, v2Definitions: v2Definitions}, nil
	}
	absoluteDirectory, err := filepath.Abs(directory)
	if err != nil {
		return nil, fmt.Errorf("resolve Flow rendering directory: %w", err)
	}
	info, err := os.Stat(absoluteDirectory)
	if err != nil {
		return nil, fmt.Errorf("open Flow rendering directory %s: %w", absoluteDirectory, err)
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("Flow rendering path is not a directory: %s", absoluteDirectory)
	}
	catalog.Configured = true
	catalog.Directory = absoluteDirectory
	if err := filepath.WalkDir(absoluteDirectory, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || !strings.EqualFold(filepath.Ext(entry.Name()), ".json") {
			return nil
		}
		definition, readErr := readFlowDefinition(absoluteDirectory, path)
		if readErr != nil {
			return readErr
		}
		catalog.Definitions = append(catalog.Definitions, definition)
		if definition.SchemaVersion == "2.0" && definition.Valid {
			if _, exists := v2Definitions[definition.FlowName]; exists {
				return fmt.Errorf("multiple valid Flow Definition Graph 2.0 files define Flow type %q", definition.FlowName)
			}
			v2Definitions[definition.FlowName] = *definition.V2
		}
		return nil
	}); err != nil {
		return nil, fmt.Errorf("load Flow rendering directory %s: %w", absoluteDirectory, err)
	}
	sort.Slice(catalog.Definitions, func(left int, right int) bool {
		return catalog.Definitions[left].ID < catalog.Definitions[right].ID
	})
	response, err := json.Marshal(catalog)
	if err != nil {
		return nil, fmt.Errorf("encode Flow Definition Graph catalog: %w", err)
	}
	return &flowDefinitionHandler{response: response, v2Definitions: v2Definitions}, nil
}

func newFlowDefinitionHandler(graph []byte) (*flowDefinitionHandler, error) {
	definition, err := flowDefinitionFromGraph("visualized-flow.json", graph)
	if err != nil {
		return nil, err
	}
	catalog := flowDefinitionCatalog{
		Configured:  true,
		Directory:   "generated by dexcli visualize",
		Definitions: []flowDefinition{definition},
	}
	v2Definitions := make(map[string]api.V2Definition)
	if definition.SchemaVersion == "2.0" && definition.Valid {
		v2Definitions[definition.FlowName] = *definition.V2
	}
	response, err := json.Marshal(catalog)
	if err != nil {
		return nil, fmt.Errorf("encode Flow Definition Graph catalog: %w", err)
	}
	return &flowDefinitionHandler{response: response, v2Definitions: v2Definitions}, nil
}

func readFlowDefinition(root string, path string) (flowDefinition, error) {
	info, err := os.Stat(path)
	if err != nil {
		return flowDefinition{}, err
	}
	if info.Size() > maxFlowDefinitionBytes {
		return flowDefinition{}, fmt.Errorf("Flow Definition Graph exceeds %d bytes: %s", maxFlowDefinitionBytes, path)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return flowDefinition{}, err
	}
	relativePath, err := filepath.Rel(root, path)
	if err != nil {
		return flowDefinition{}, err
	}
	relativePath = filepath.ToSlash(relativePath)
	return flowDefinitionFromGraph(relativePath, data)
}

func flowDefinitionFromGraph(file string, graph []byte) (flowDefinition, error) {
	var header flowDefinitionHeader
	if err := json.Unmarshal(graph, &header); err != nil {
		return flowDefinition{}, fmt.Errorf("parse Flow Definition Graph %s: %w", file, err)
	}
	if header.SchemaVersion != "1.0" && header.SchemaVersion != "2.0" {
		return flowDefinition{}, fmt.Errorf("Flow Definition Graph %s has unsupported schemaVersion %q", file, header.SchemaVersion)
	}
	if header.Source.Language != "go" && header.Source.Language != "python" {
		return flowDefinition{}, fmt.Errorf("Flow Definition Graph %s has unsupported source language %q", file, header.Source.Language)
	}
	if header.SchemaVersion == "2.0" && header.Source.Language != "go" {
		return flowDefinition{}, fmt.Errorf("Flow Definition Graph 2.0 %s must use Go source", file)
	}
	if header.Nodes == nil || header.Edges == nil || header.Diagnostics == nil {
		return flowDefinition{}, fmt.Errorf("Flow Definition Graph %s must contain nodes, edges, and diagnostics arrays", file)
	}
	if header.SchemaVersion == "2.0" && (header.Groups == nil || header.V2 == nil) {
		return flowDefinition{}, fmt.Errorf("Flow Definition Graph 2.0 %s must contain groups and v2", file)
	}
	if header.SchemaVersion == "2.0" {
		if err := validateFlowDefinitionV2(file, graph, header); err != nil {
			return flowDefinition{}, err
		}
	}
	flowName := strings.TrimSpace(header.Flow.Name)
	if flowName == "" {
		flowName = strings.TrimSuffix(file, filepath.Ext(file))
	}
	return flowDefinition{
		ID:             file,
		File:           file,
		SchemaVersion:  header.SchemaVersion,
		FlowName:       flowName,
		SourceLanguage: header.Source.Language,
		SourcePath:     header.Source.Path,
		Valid:          header.Valid,
		Graph:          graph,
		V2:             header.V2,
	}, nil
}

func validateFlowDefinitionV2(file string, graph []byte, header flowDefinitionHeader) error {
	var document map[string]json.RawMessage
	if err := json.Unmarshal(graph, &document); err != nil {
		return fmt.Errorf("parse Flow Definition Graph 2.0 %s: %w", file, err)
	}
	allowedTopLevel := map[string]bool{
		"schemaVersion": true, "valid": true, "source": true, "flow": true,
		"nodes": true, "edges": true, "diagnostics": true, "groups": true, "v2": true,
	}
	for _, field := range []string{"schemaVersion", "valid", "source", "flow", "nodes", "edges", "diagnostics", "groups", "v2"} {
		if _, exists := document[field]; !exists {
			return fmt.Errorf("Flow Definition Graph 2.0 %s is missing field %q", file, field)
		}
	}
	for field := range document {
		if !allowedTopLevel[field] {
			return fmt.Errorf("Flow Definition Graph 2.0 %s has unknown field %q", file, field)
		}
	}
	if err := validateFlowDefinitionObjectFields(document["source"], []string{"language", "path"}, []string{"language", "path"}); err != nil {
		return fmt.Errorf("Flow Definition Graph 2.0 %s has malformed source: %w", file, err)
	}
	if err := validateFlowDefinitionObjectFields(document["flow"], []string{"name", "startStepId", "span"}, []string{"name"}); err != nil {
		return fmt.Errorf("Flow Definition Graph 2.0 %s has malformed flow: %w", file, err)
	}
	type group struct {
		ID      string   `json:"id"`
		Label   string   `json:"label"`
		StepIDs []string `json:"stepIds"`
	}
	var groups []group
	if err := decodeStrictFlowDefinitionJSON(document["groups"], &groups); err != nil {
		return fmt.Errorf("Flow Definition Graph 2.0 %s has malformed groups: %w", file, err)
	}
	groupIDs := make(map[string]bool, len(groups))
	stepIDs := make(map[string]bool)
	for _, group := range groups {
		if !flowDefinitionGroupIDPattern.MatchString(group.ID) || strings.TrimSpace(group.Label) == "" || len(group.StepIDs) == 0 {
			return fmt.Errorf("Flow Definition Graph 2.0 %s has an invalid group", file)
		}
		if groupIDs[group.ID] {
			return fmt.Errorf("Flow Definition Graph 2.0 %s repeats group %q", file, group.ID)
		}
		groupIDs[group.ID] = true
		for _, stepID := range group.StepIDs {
			if stepID == "" || stepIDs[stepID] {
				return fmt.Errorf("Flow Definition Graph 2.0 %s has an invalid or repeated grouped Step ID", file)
			}
			stepIDs[stepID] = true
		}
	}
	var definition api.V2Definition
	if err := decodeStrictFlowDefinitionJSON(document["v2"], &definition); err != nil {
		return fmt.Errorf("Flow Definition Graph 2.0 %s has malformed v2: %w", file, err)
	}
	if err := validateV2Definition(definition); err != nil {
		return fmt.Errorf("Flow Definition Graph 2.0 %s has invalid v2: %w", file, err)
	}
	if header.V2 == nil {
		panic("validated v2 must be present")
	}
	*header.V2 = definition
	return nil
}

func decodeStrictFlowDefinitionJSON(data []byte, target interface{}) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	decoder.UseNumber()
	return decoder.Decode(target)
}

func validateFlowDefinitionObjectFields(data []byte, allowed []string, required []string) error {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	allowedFields := make(map[string]bool, len(allowed))
	for _, field := range allowed {
		allowedFields[field] = true
	}
	for field := range object {
		if !allowedFields[field] {
			return fmt.Errorf("unknown field %q", field)
		}
	}
	for _, field := range required {
		if _, exists := object[field]; !exists {
			return fmt.Errorf("missing field %q", field)
		}
	}
	return nil
}

func validateV2Definition(definition api.V2Definition) error {
	indexedKeys := make(map[string]bool, len(definition.IndexedAttributes))
	indexKeys := make(map[string]bool, len(definition.IndexedAttributes))
	for _, attribute := range definition.IndexedAttributes {
		if attribute.AttributeKey == "" || !v2IndexKeyPattern.MatchString(attribute.IndexKey) ||
			!validV2IndexType(attribute.IndexType, attribute.ValueType) {
			return fmt.Errorf("indexed Attribute %q has invalid metadata", attribute.AttributeKey)
		}
		if indexedKeys[attribute.AttributeKey] || indexKeys[attribute.IndexKey] {
			return fmt.Errorf("indexed Attribute or index key is repeated")
		}
		indexedKeys[attribute.AttributeKey] = true
		indexKeys[attribute.IndexKey] = true
	}
	if definition.Summary.RPCName != "GetDexSummary" || definition.Display.RPCName != "GetDexDisplay" {
		return fmt.Errorf("Summary and Display must use their fixed RPC names")
	}
	if err := validateV2View(definition.Summary, false, indexedKeys); err != nil {
		return fmt.Errorf("Summary: %w", err)
	}
	if err := validateV2View(definition.Display, true, nil); err != nil {
		return fmt.Errorf("Display: %w", err)
	}
	actionNames := make(map[string]bool, len(definition.Actions))
	for _, action := range definition.Actions {
		if action.RPCName == "" || strings.TrimSpace(action.Label) == "" || actionNames[action.RPCName] {
			return fmt.Errorf("Action RPC name and label must be non-empty and unique")
		}
		actionNames[action.RPCName] = true
		if !v2ActionPermissionPattern.MatchString(action.RequiredPermission) {
			return fmt.Errorf("Action %q has an invalid required permission %q", action.RPCName, action.RequiredPermission)
		}
		if action.Condition.AttributeKey == "" || action.Condition.Operator != "in" || len(action.Condition.Values) == 0 {
			return fmt.Errorf("Action %q has an invalid condition", action.RPCName)
		}
		for _, value := range action.Condition.Values {
			switch value.(type) {
			case string, json.Number, bool:
			default:
				return fmt.Errorf("Action %q condition values must be JSON scalars", action.RPCName)
			}
		}
		if err := validateV2ActionInput(action.Input); err != nil {
			return fmt.Errorf("Action %q: %w", action.RPCName, err)
		}
	}
	return nil
}

func validV2IndexType(indexType string, valueType string) bool {
	compatible := map[string]string{
		"keyword": "string", "fulltext": "string", "keyword-array": "string-array",
		"int": "int64", "double": "double", "bool": "bool", "datetime": "datetime",
	}
	return compatible[indexType] == valueType
}

func validateV2View(
	view api.V2RPCView,
	canEdit bool,
	forbiddenKeys map[string]bool,
) error {
	seen := make(map[string]bool, len(view.Fields))
	claimedUISlots := make(map[string]string, len(view.Fields))
	for _, field := range view.Fields {
		if field.AttributeKey == "" || !validV2ViewType(field.ValueType) || seen[field.AttributeKey] {
			return fmt.Errorf("field %q has invalid metadata", field.AttributeKey)
		}
		if field.Editable && (!canEdit || !validV2EditableType(field.ValueType)) {
			return fmt.Errorf("field %q cannot be editable", field.AttributeKey)
		}
		if forbiddenKeys[field.AttributeKey] {
			return fmt.Errorf("field %q duplicates an indexed Attribute", field.AttributeKey)
		}
		if err := claimV2UISlot(field, claimedUISlots); err != nil {
			return err
		}
		seen[field.AttributeKey] = true
	}
	return nil
}

// UI slots a field may claim, mapped to whether only one field per view may claim each.
//
// Repeated here rather than imported from the analyzer because a Flow Definition Graph can reach the
// server from anywhere, so the server cannot assume the analyzer wrote it.
var v2ViewUISlots = map[string]bool{
	"title":          true,
	"subtitle":       true,
	"status":         true,
	"recommendation": true,
	"reason":         false,
}

func claimV2UISlot(field api.V2ViewField, claimedUISlots map[string]string) error {
	if field.UISlot == "" {
		return nil
	}
	unique, known := v2ViewUISlots[field.UISlot]
	if !known {
		return fmt.Errorf("field %q claims unknown UI slot %q", field.AttributeKey, field.UISlot)
	}
	if !unique {
		return nil
	}
	if holder, taken := claimedUISlots[field.UISlot]; taken {
		return fmt.Errorf("UI slot %q is claimed by both %q and %q", field.UISlot, holder, field.AttributeKey)
	}
	claimedUISlots[field.UISlot] = field.AttributeKey
	return nil
}

func validV2ViewType(valueType string) bool {
	switch valueType {
	case "string", "string-array", "int64", "double", "bool", "datetime", "json", "object", "array", "attribute-map":
		return true
	default:
		return false
	}
}

func validV2EditableType(valueType string) bool {
	switch valueType {
	case "string", "int64", "double", "bool", "datetime":
		return true
	default:
		return false
	}
}

func validateV2ActionInput(input api.V2ActionInput) error {
	if input.Kind == "none" {
		if len(input.Fields) != 0 {
			return fmt.Errorf("none input must not declare fields")
		}
		return nil
	}
	if input.Kind != "object" || len(input.Fields) == 0 {
		return fmt.Errorf("input kind must be none or a non-empty object")
	}
	seen := make(map[string]bool, len(input.Fields))
	for _, field := range input.Fields {
		if field.FieldName == "" || !validV2EditableType(field.ValueType) || seen[field.FieldName] {
			return fmt.Errorf("input field %q has invalid metadata", field.FieldName)
		}
		if field.Source == "attribute" && field.AttributeKey == "" {
			return fmt.Errorf("attribute input field %q requires attributeKey", field.FieldName)
		}
		if field.Source == "user" && field.AttributeKey != "" {
			return fmt.Errorf("user input field %q forbids attributeKey", field.FieldName)
		}
		if field.Source != "user" && field.Source != "attribute" {
			return fmt.Errorf("input field %q has invalid source", field.FieldName)
		}
		seen[field.FieldName] = true
	}
	return nil
}

func (h *flowDefinitionHandler) V2Definitions() map[string]api.V2Definition {
	definitions := make(map[string]api.V2Definition, len(h.v2Definitions))
	for flowType, definition := range h.v2Definitions {
		definitions[flowType] = definition
	}
	return definitions
}

func (h *flowDefinitionHandler) ServeHTTP(response http.ResponseWriter, _ *http.Request) {
	response.Header().Set("Content-Type", "application/json; charset=utf-8")
	response.WriteHeader(http.StatusOK)
	if _, err := response.Write(h.response); err != nil {
		panic(fmt.Sprintf("write Flow Definition Graph catalog: %v", err))
	}
}
